# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_assettype_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='status',
            field=models.CharField(default='', max_length=30, verbose_name='状态'),
        ),
    ]
